server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:challenge-first/config-file.git
#        encrypt:
#          enabled: false
  application:
    name: config-service

encrypt:
  key: ${TEST_KEY}